ok

diff --git a/.github/workflows/tfvetdemo.yaml b/.github/workflows/tfvetdemo.yaml
--- a/.github/workflows/tfvetdemo.yaml
+++ b/.github/workflows/tfvetdemo.yaml
@@ -64,21 +64,23 @@ jobs:
               terraform plan -out=test.tfplan
               terraform show -json ./test.tfplan > ./tfplan.json
               ls
-              VIOLATIONS=$(gcloud beta terraform vet tfplan.json --policy-library=./vet-policy-library --format=json) 
-              echo "Violations gathered"
-              retVal=$?
-              if [ $retVal -eq 2 ]; then
-                # Optional: parse the VIOLATIONS variable as json and check the severity level
-                echo "$VIOLATIONS"
-                echo "Violations found; not proceeding with terraform apply"
-                exit 1
-              fi
-              if [ $retVal -ne 0]; then
-                echo "Error during gcloud beta terraform vet; not proceeding with terraform apply"
-                exit 1
-              fi
+              gcloud beta terraform vet tfplan.json --policy-library=./vet-policy-library --format=json
 
-              echo "No policy violations detected; proceeding with terraform apply"
+              # VIOLATIONS=$(gcloud beta terraform vet tfplan.json --policy-library=./vet-policy-library --format=json) 
+              # echo "Violations gathered"
+              # retVal=$?
+              # if [ $retVal -eq 2 ]; then
+              #   # Optional: parse the VIOLATIONS variable as json and check the severity level
+              #   echo "$VIOLATIONS"
+              #   echo "Violations found; not proceeding with terraform apply"
+              #   exit 1
+              # fi
+              # if [ $retVal -ne 0]; then
+              #   echo "Error during gcloud beta terraform vet; not proceeding with terraform apply"
+              #   exit 1
+              # fi
+
+              # echo "No policy violations detected; proceeding with terraform apply"
 
 
     
